### ISSUE TITLE
ERROR in The pipe 'mutable' could not be found

### ISSUE THREAD

**Issue by YogliB** [ngxs-labs/data#142]
`"@ngxs-labs/data": "2.4.1",`

```html
<div>
	<full-calendar
		*ngIf="calendarState$ | async | mutable as calendarState"
		#calendar
		[plugins]="calendarState.plugins"
	></full-calendar>
</div>
```

* I have the `NgxsDataPluginModule` imported in my Store module.

What am I missing?

**Comment by splincode** [comment]
hmmm, I forgot any else?

https://github.com/ngxs-labs/data/blob/master/src/lib/ngxs-data.module.ts#L10
