### ISSUE TITLE
How to use it in resolver?

### ISSUE THREAD

**Issue by miguelramos** [ngxs-labs/data#158]
I'm not able to set state in a resolver. Any tips to how to do it? Current i have the following code:

Service:

````

@Injectable()
export class HomeService {
  constructor(
    private readonly urlService: HttpUrlService,
    private readonly httpService: HttpClient
  ) { }

  public fetchAll() {
    const url = this.urlService.get('HOME.FETCH');

    return this.httpService.get<{data: HomeModel}>(url).pipe(
      map(response => response.data)
    );
  }
}

````
State:

````
@StateRepository()
@State<HomeModel>({
  name: 'home',
  defaults: {
    title: null,
    description: null
  }
})
@Injectable()
export class HomeState extends NgxsDataRepository<HomeModel> {
  @Select(state => state.home)
  public home$: Observable<HomeModel>;

  constructor(
    private readonly homeService: HomeService
  ) {
    super();
  }

  @action()
  public getContent() {
    // this does a httpClient.get()
    return this.homeService.fetchAll().pipe(
      tap(content => this.ctx.setState(() => content ))
    );
  }
}
````

Then in resolver:

````

@Injectable()
export class HomeResolver implements Resolve<any> {
  constructor(
    private homeState: HomeState
  ) { }

  public resolve() {
    return this.homeState.getContent();
  }
}

````

But checking redux tools there is no diff in the state:

![image](https://user-images.githubusercontent.com/495720/73225907-2ca98c00-4166-11ea-8655-de9bfcf73c76.png)

I'm only able if i explicity .subscribe() the observable, but with that i loose the purpose of a resolver.

On other hand, use it normally as async bind in the view i get the data from the request:

````
@Component({
  selector: 'ng-lab-home',
  templateUrl: './home.component.html',
  styleUrls: ['./home.component.scss']
})
export class HomeComponent implements OnInit {
  home$: Observable<HomeModel>;

  constructor(
    private readonly homeState: HomeState
  ) {}

  ngOnInit() {
    this.home$ = this.homeState.home$;
  }

}

````

````
<div class="ui-hero" *ngIf="(home$ | async) as home">
  <h1 class="ui-hero__title">{{home.title}}</h1>
  <p class="ui-hero__info">{{home.description}}</p>
</div>
````

So i'm a bit confuse because i set state with .setState() and i don't see the data in the state (redux devtools), but using as normal observable data get's renderer in component, is like doesn't set anything related with state but throws data normally thru observables pipes.

**Comment by splincode** [comment]
Very strange, maybe it is bug. Create stackblitz example for me and and then I can quickly investigate the problem

**Comment by miguelramos** [comment]
@splincode thanks for your quick answer, and i will create a stackblitz to replicate the issue. Meanwhile i will try to debug and see i can get more info to give you.

**Comment by miguelramos** [comment]
@splincode here is the link for the stackblitz: https://stackblitz.com/edit/angular-pvbx97

**Comment by splincode** [comment]
thank you!

**Comment by splincode** [comment]
@miguelramos Sorry, I was able to get to study the problem just now, and actually

There really is a big difference between `this.ctx.setState` and `this.setState`.

in devtool you will see a state change only when the action is called

`this.setState` - is action
`this.ctx.setState` - directly change state without calling an action

```ts
@StateRepository()
@State<HomeModel>({
  name: 'home',
  defaults: {
    title: null,
    description: null
  }
})
@Injectable()
export class HomeState extends NgxsDataRepository<HomeModel> {
  constructor(private readonly homeService: HomeService) {
    super();
  }

  // basic http request (not needed action, because finished before setState)
  public getContent() {
    return this.homeService.fetchAll().pipe(tap(content => {
      this.setState(content); // call action (if we need see in devtools information about it)
   }));
  }
}
```

![image](https://user-images.githubusercontent.com/12021443/76527354-21918d80-6480-11ea-88ac-ec71ed5518da.png)

https://stackblitz.com/edit/angular-ua9xge

**Comment by miguelramos** [comment]
@splincode thanks for the input, and yes changing ctx.setState to setState it works as expected, but this should be documented to know the diferences between it.

**Comment by splincode** [comment]
https://github.com/ngxs-labs/data/blob/master/docs/pages/action.md#what-difference-between-thisctxsetstate-and-thissetstate
