### ISSUE TITLE
Argument of type is not assignable to parameter of type error with store operator updateItem

### ISSUE THREAD

**Issue by ishanuda** [ngxs-labs/data#172]
Hi,
I am getting the following error when using the operator `updateItem`
with data-plugin "@ngxs-labs/data": "^2.4.1" and above,

![data-plugin-error](https://user-images.githubusercontent.com/8893919/74323801-16c5d900-4dac-11ea-9a68-4dd37a6a2fef.jpg)

[Example @ stackblitz:](https://stackblitz.com/edit/angular-mj2r4s?file=src%2Fapp%2Fstore%2Ftodo%2Ftodo.state.ts)

I don't know if this problem comes with other operators as well.
Thank you

**Comment by jmbe** [comment]
As far as I can tell `StateOperator<T> = (existing: Readonly<T>) => T` is not supported at at all, so I'm guessing the origins of ngxs-labs/data predates state operators? It would be awesome to see support, and would also help migrating existing code which already uses state operators. I'm using immer as a substitute in the mean time, but of course state operators would be more in line with regular ngxs/store.

**Comment by splincode** [comment]
Works for me

```ts
this.ctx.setState(
   patch<Immutable<TodoStateModel>>({
     todos: updateItem<Todo>(index, patch({ completed: (value) => !value }))
   })
);
```
