### ISSUE TITLE
Initialization of NgxsDataPluginModule in a non-app module

### ISSUE THREAD

**Issue by st-clair-clarke** [ngxs-labs/data#21]
Hi, in your example, to register the NgxsDataPluginModule in the app module the following is used:

```
...
NgxsDataPluginModule.forRoot({ factory: StateFactory, context: StateContextFactory })
...
```

How do I accomplish same in a non-app module - there is no NgxsDataPluginModule.forChild() or NgxsDataPluginModule.forFeature() (as is present in NgxsModule.forFeature())

**Comment by st-clair-clarke** [comment]
Thanks for your prompt reply. My data is substantial. If I do this in app.module, it will cause unacceptable bloating.

>>In the future you do not have to do it ngxs/store#1325
Any idea how far is the future?

**Comment by splincode** [comment]
Maybe add `NgxsDataPluginModule.forRoot({ factory: StateFactory, context: StateContextFactory })` to SharedModule?
