### ISSUE TITLE
Problem returning from action with an explicit tysecript class as an explicit payload

### ISSUE THREAD

**Issue by st-clair-clarke** [ngxs-labs/data#25]
Hi, I am trying to follow the example at [https://github.com/ngxs-labs/data](https://github.com/ngxs-labs/data). However, I am using an explicit typescript class as a payload, and having difficulties in what to return from the action. I would like your help in what should be return in the addAddress and updateAddress actions

```
import { action, Immutable, NgxsDataRepository, query } from '@ngxs-labs/data'
import { Observable } from 'rxjs'

export interface IFormState {
  dirty?: boolean
  model?: any
}

export class FormState {
  dirty?: boolean = false
  model?: any = undefined
}

export interface IRegistrationStateModel {
  address: IFormState
}

export class RegistrationStateModel {
  address = new FormState()
}

export class RegistrationState extends NgxsDataRepository<IRegistrationStateModel>{
  @query<IRegistrationStateModel, IFormState>((state) => state.address)
  public address$: Observable<IFormState>
  
  @action() addAddress():Immutable<IRegistrationStateModel>{
    return this.ctx.setState((state: Immutable<IRegistrationStateModel>) => address: state.address)
  }
  
  
  @action() updatedAddress():Immutable<IRegistrationStateModel>{
    return 
    
  }
  
}
```

**Comment by splincode** [comment]
Please add stackblitz

**Comment by splincode** [comment]
what do you mean?
>  I am using an explicit typescript class as a payload

**Comment by st-clair-clarke** [comment]
Instead of using 

{
  dirty?: boolean = false
  model?: any = undefined
}

I use instead: 
export class FormState {
  dirty?: boolean = false
  model?: any = undefined
}

**Comment by splincode** [comment]
Okay, what exactly is the problem?

**Comment by splincode** [comment]
addAddress, updatedAddress
These are the usual methods, you can return anything

**Comment by st-clair-clarke** [comment]
Given the addAddress and updateAddress methods above, how do I set and update the address property of the RegistrationStateModel and print that to the console. Yes they are usual methods but I am doing something wrong.

**Comment by st-clair-clarke** [comment]
The problem is that the => address: property in addAddress CANNOT BE FOUND.

**Comment by splincode** [comment]
```ts
@StateRepository()
@State< IRegistrationStateModel>({ .. })
export class RegistrationState extends NgxsDataRepository<IRegistrationStateModel>{
  @query<IRegistrationStateModel, IFormState>((state) => state.address)
  public address$: Observable<IFormState>
  
  @action() addAddress(newAdress: IFormState):Immutable<IRegistrationStateModel>{
    return this.ctx.setState((state: Immutable<IRegistrationStateModel>) => ({ 
       address: newAdress
    });
  }

}
```

```ts
@Component()
class AppComponent {
  constructor(private registration: RegistrationState) {}

  public ngOnInit() {
     this.registration.addAddress({ dirty: true, model: { hello: 'world' }  });
  }
}
```

**Comment by st-clair-clarke** [comment]
I am getting IDE generated errors from your example. Did it actually work for you? See error in graphic. Thanks

![erors](https://user-images.githubusercontent.com/3227590/65766975-5764d480-e0e1-11e9-993d-aeea0e999c69.png)

**Comment by splincode** [comment]
I would like to see stackblitz example

**Comment by st-clair-clarke** [comment]
Will set it up. Thanks

**Comment by st-clair-clarke** [comment]
See [https://angular-7zt9gq.stackblitz.io](https://angular-7zt9gq.stackblitz.io)

**Comment by st-clair-clarke** [comment]
The stackblitz example is not printing the store's state correctly to the console when the app is run.

**Comment by splincode** [comment]
@st-clair-clarke can you explain what is wrong?

![image](https://user-images.githubusercontent.com/12021443/65821824-85fac080-e243-11e9-89b2-5d832ff25916.png)

https://stackblitz.com/edit/angular-7zt9gq

According to what you do in the code, everything works as it should

**Comment by splincode** [comment]
The only thing I do not recommend using is

```ts
export class RegistrationStateModel {
  address = new FormState()
}
```

It is necessary to use the concept of POJO. POJO stands for Plain Old Java Object. It is an ordinary object, not bound by any special restriction other than those forced by the Language Specification and not requiring any class path. POJOs are used for increasing the readability and re-usability of a program.

![image](https://user-images.githubusercontent.com/12021443/65821890-716af800-e244-11e9-91e3-e65836eb79b8.png)

**Comment by splincode** [comment]
also you can simplify

![image](https://user-images.githubusercontent.com/12021443/65821926-bd1da180-e244-11e9-939d-a68b48e0f757.png)

**Comment by st-clair-clarke** [comment]
@splincode 

![image](https://user-images.githubusercontent.com/3227590/65823199-b1ab8580-e206-11e9-977d-3f1e6ed0b021.png)
