### ISSUE TITLE
Error: Uncaught (in promise): Error: Class extends value undefined is not a constructor or null

### ISSUE THREAD

**Issue by splincode** [ngxs-labs/data#268]
https://stackblitz.com/edit/ngxs-labs-data-9cnqqr?file=undefined

**Comment by gtamas** [comment]
@splincode 
Guys, I'm planing to use this in one of my upcoming projects,  but I can see it's not production ready yet. About when can we expect the first prod release?

Could there be a prod release in the next 3 months?

**Comment by splincode** [comment]
@gtamas So far, the release candidate, but you can try to use it already!

**Comment by splincode** [comment]
https://github.com/ngxs-labs/data/milestone/1
![image](https://user-images.githubusercontent.com/12021443/77360994-7c1fc900-6d5f-11ea-9792-8737fb4123ad.png)
