### ISSUE TITLE
IE Support?

### ISSUE THREAD

**Issue by gtamas** [ngxs-labs/data#278]
Guys, do you have any plans to add support for IE11 (at least)?

I would love to use this in my project, but we have to support IE (unfortunately). Will IE 10 / 11 ever be supported?

Also, do you have a roadmap for this lib? About when can we expect it to be prod ready? The labs page says it's "stable".

**Comment by splincode** [comment]
1. If you need IE, you must add proxy class polyfill for your project

https://github.com/GoogleChrome/proxy-polyfill

2. About roadmap 
what do you mean? we have milestone in repo

**Comment by gtamas** [comment]
@splincode 
Thanks for the IE info, great news!

Roadmap: I can see there is a 3.0 milestone, but in the meantime, the description of the project still says "not production ready yet". So I just want to know how far is "3.0" from "prod ready"?

In your estimation, will you reach prod ready status anytime soon?

**Comment by splincode** [comment]
"not production ready yet" - fixed, it's ready

`Like in 1-2 months` - true

```
What I wanna figure out is whether is it a good idea to integrate this extension into a project which will be released in a couple of months.
```

up to you

**Comment by gtamas** [comment]
ok thx
