### ISSUE TITLE
Support async storage for persistence decorator

### ISSUE THREAD

**Issue by splincode** [ngxs-labs/data#299]

**Comment by SteveLemire** [comment]
I was able to manage our own storage service that provides functionality to support async storage with the help of [StorageMap ](https://www.npmjs.com/package/@ngx-pwa/local-storage) library that use _IndexedDb_ and [AsyncStorageEngine](https://github.com/ngxs-labs/async-storage-plugin).

1. Install [StorageMap ](https://www.npmjs.com/package/@ngx-pwa/local-storage).

2. Install [AsyncStorageEngine](https://github.com/ngxs-labs/async-storage-plugin)

3. Create a new storage service and implement AsyncStorageEngine with missing members like this:
```
export class StorageService implements AsyncStorageEngine {
  constructor(private storageMap: StorageMap}
```

4. In your _app.module.ts_, configure your NgxsModule and other packages like this:
```
    NgxsModule.forRoot(
      [
        // Add your state classes here
      ],
      {
        developmentMode: !environment.production,
        selectorOptions: {
          // https://www.ngxs.io/concepts/select#selector-options
          // These Selector Settings are recommended in preparation for NGXS v4
          suppressErrors: false,
          injectContainerState: false,
        },
      },
    ),
    // https://github.com/ngxs-labs/async-storage-plugin
    NgxsAsyncStoragePluginModule.forRoot(StorageService),
   // https://github.com/ngxs-labs/async-storage-plugin
    NgxsDataPluginModule.forRoot([NGXS_DATA_STORAGE_PLUGIN]),
```

5. In your state class, add the following decorators:
```
@Persistence({
  useClass: StorageService,
})
@StateRepository()
@State<MyStateModel>({...
```

Et voilà! 
You can now use your async _StorageService_ with NGXS!

> Note: This will not work with IE11 and target type ES5 because ngxs-lab/data _@Persistence_ decorator use the _Package_ class that is only available with ES6 (ES2015). I was not able get this work event if I tried with the following packages:
> - https://github.com/GoogleChrome/proxy-polyfill
> - https://github.com/tvcutsem/harmony-reflect
>

**Comment by splincode** [comment]
Ohh, great))  you are awesome

What do you think about
that is, we could develop adapters in this plugin, with good support

```ts
import { NGXS_DATA_ASYNC_STORAGE_PLUGIN } from '@ngxs-labs/data/async-storage';

NgxsDataPluginModule.forRoot([
   NGXS_DATA_ASYNC_STORAGE_PLUGIN,
   NGXS_DATA_STORAGE_PLUGIN
])
```

instead NgxsAsyncStoragePluginModule

**Comment by floinay** [comment]
hi, do you have any plans for this?

**Comment by splincode** [comment]
Move to https://github.com/Angular-RU/angular-ru-sdk/issues/864
