### ISSUE TITLE
Proxy is a ES2015 class that is not compatible with IE11 with ES5 target

### ISSUE THREAD

**Issue by SteveLemire** [ngxs-labs/data#420]
Hi,
 
I would like to use the package [ngxs-lab data](https://github.com/ngxs-labs/data) in my Angular 9 application but I have an issue to make it run with IE11 and ES5 target compatibility event if the readme say that the IE browser (IE + polyfills) is compatible.

![image](https://user-images.githubusercontent.com/18408683/82079569-0e35b500-96b1-11ea-997d-57bb496887a6.png)

When running the application with _@Persistance()_ attribute on my State class, at the moment Angular try to set the decorator, it throw an exception. This is because the Proxy class used in lib\decorators\src\persistence\persistence.ts is defined with es2015 (lib.es2015.proxy.d.ts)

![image](https://user-images.githubusercontent.com/18408683/82079798-75ec0000-96b1-11ea-89c2-0225641988da.png)

I also try to use the google _proxy-polyfill_: https://github.com/GoogleChrome/proxy-polyfill
It failed because angular try to set an undefined property:

![image](https://user-images.githubusercontent.com/18408683/82079850-8ac89380-96b1-11ea-82ed-38950adae4d3.png)

Can you please help to run your awesome ngxs-labs/data package and make it works with IE11 and target ES5 ? Do you think of any way I can fix this?

Maybe you please add the proxy-polyfill directly in your library to support older browser and ES5 target.

Thanks!

**Comment by splincode** [comment]
Sorry, most likely this will not be considered a bug, since we no longer support Internet Explorer

![image](https://user-images.githubusercontent.com/12021443/83954786-e4595380-a854-11ea-9df2-59b08fafb763.png)

**Comment by splincode** [comment]
Release v4.0
