### ISSUE TITLE
ng v9.1.7 does not update local/session storage

### ISSUE THREAD

**Issue by ishanuda** [ngxs-labs/data#427]
Hi,
I updated the angular to v9.1.7 and the data library to v3.0.5.
Now the library does not update the values in local/ session storage.

[Minimal repo](https://github.com/ishanuda/ngxs-data-issue-mr-1)
NOTE: repo URL changed

Thank you very much.

**Comment by YogliB** [comment]
any idea what's causing this?

**Comment by splincode** [comment]
@ishanuda @YogliB https://github.com/angular/angular/issues/37476

this is bug Angular I think

**Comment by splincode** [comment]
Workaround disable Ivy before fixed

```
"angularCompilerOptions": {
    "enableIvy": false
  }
```

**Comment by ishanuda** [comment]
Hi,
Thank you for your support.
Will look in to forward till the but is fixed in the NG
Regards

**Comment by splincode** [comment]
@ishanuda Release v4.0
