### ISSUE TITLE
Warning: Entry point '@ngxs-labs/data' contains deep imports

### ISSUE THREAD

**Issue by ishanuda** [ngxs-labs/data#430]
Hi,
I am getting the following warning when trying to compile the project

Warning: Entry point '@ngxs-labs/data' contains deep imports into '../node_modules/@ngxs/store/src/internal/internals'. 
This is probably not a problem but may cause the compilation of entry points to be out of order.  

Configurations:

"typescript": "~3.7.5"
"@angular/cli": "^9.1.7",
"@angular/core": "^9.1.9",
"@ngxs/store": "^3.6.2",
"@ngxs-labs/data": "^2.4.1",

Thank you very much

**Comment by splincode** [comment]
Create github repo also for reproduce, please

**Comment by ishanuda** [comment]
Hi,
Repo created.
[Repo](https://github.com/ishanuda/ngxs-data-issue-mr-2)
Thank you

**Comment by splincode** [comment]
fixed: https://github.com/ngxs-labs/data/pull/454

**Comment by ishanuda** [comment]
HI,
Thank you very much for the fix.

Is this fix available in V2.x.x as well?

Shall I delete the min repo created for the test?

Regards

**Comment by splincode** [comment]
Sorry only v3 fix, but isn’t a problem for Angular 8

**Comment by ishanuda** [comment]
Hi,
Is this update available to test with NG v9 by disabling ivy?
Regards

**Comment by splincode** [comment]
> Is this update available to test with NG v9 by disabling ivy?

yes

**Comment by splincode** [comment]
Released in 3.0.6
