### ISSUE TITLE
Managing the wiki for the documentation

### ISSUE THREAD

**Issue by ishanuda** [ngxs-labs/data#460]
Hi,
It would be great if you can move the library-related documents to the wiki in order to manage proper documentation.

**Reference:**
[Github wiki help](https://help.github.com/en/github/building-a-strong-community/about-wikis)

**Example:**
[Good example](https://github.com/angular/flex-layout/wiki)

Thank you very much.

**Comment by splincode** [comment]
Unfortunately, I don’t have much free time and so far I understand that it’s easier to keep documentation in md files

**Comment by ishanuda** [comment]
Closing the issue.
