### ISSUE TITLE
Data Action Doc needs updating?

### ISSUE THREAD

**Issue by BillyGoatsOats** [ngxs-labs/data#472]
https://github.com/ngxs-labs/data/blob/master/docs/pages/data-action.md shows that you can use payloads w/out the `@Payload` decorator but https://github.com/ngxs-labs/data/blob/master/CHANGELOG.md and recently updated examples suggest: `"now it is necessary to use the payload decorator for logging send value:"`.

_P.S._ I am converting an app w/ a lot of NgRx boilerplate to use NGXS instead. I'm finding `ngxs-labs/data` to be even less boilerplate and low friction sublime state management!

I am tempted dive in heads first with the data extension, realizing this is a beta/labs plugin but seeing active development it might become the preferred way to do NGXS. Thoughts?

**Comment by splincode** [comment]
I use it in production :)

**Comment by splincode** [comment]
What do you mean about updating?

**Comment by BillyGoatsOats** [comment]
The https://github.com/ngxs-labs/data/blob/master/docs/pages/data-action.md shows usages of the actions w/ payload without the `@Payload` decorator, not sure if this is deprecated or still recommended usage, but I would imagine it should be updated to specify that you should use the `@Payload` decorator.

**Comment by splincode** [comment]
Send pull request please :)

**Comment by BillyGoatsOats** [comment]
I opened a PR with proposed documentation updates. As a follow up I think it should be mentioned that `@DataAction()` does not automatically subscribe to returned observables in the same way that `@Action` does (according to https://www.ngxs.io/concepts/state#async-actions). I found that in the `Person` example the Observable is likely being subscribed to automatically by the resolver but in my work I had to call subscribe as so:
```ts
@DataAction() setPinchValveState(@Payload('pinchValveUpdate') payload: PinchValveUpdatePayload) {
        return this.instrumentService.setPinchValve(payload.valve_number, payload.open).pipe(tap((content): void => console.log(content)));
    }
```

```ts
openPinchValve(valveNumber: number) {
        this.pinchValvesState.setPinchValveState({open: true, valve_number: valveNumber}).subscribe();
    }
```

**Comment by splincode** [comment]
Recommended 

```ts
@DataAction() setPinchValveState(@Payload('pinchValveUpdate') payload: PinchValveUpdatePayload): Observable<Content> {
        return this.instrumentService.setPinchValve(payload.valve_number, payload.open);
    }
```

```ts
openPinchValve(valveNumber: number): void {
        this.pinchValvesState.setPinchValveState({open: true, valve_number: valveNumber})
               .pipe(takeUntil(this.destroy$))
               .subscibe((content): void => console.log(content));
    }

```

**Comment by BillyGoatsOats** [comment]
cool I'll work with that.

**Comment by BillyGoatsOats** [comment]
I found this method (which is what I think @splincode is recommending with `this.destroy$`) https://alligator.io/angular/takeuntil-rxjs-unsubscribe/ to be a little messy so I am going to give this package a shot: https://github.com/ngneat/until-destroy
