### ISSUE TITLE
@DataAction returning observables in subscribe function of any action handlers throws a "Cannot read property 'pipe of null'

### ISSUE THREAD

**Issue by swatiqman** [ngxs-labs/data#483]
![ngxs observable call error](https://user-images.githubusercontent.com/23726762/85220018-e7e1f400-b397-11ea-8a18-506e2e9dc631.png)

i cant seem to call any @DataAction returning observable in subscribe function of action handlers throws an error (not even through pipe with switchMap)....am i missing something?

  this.actions$.pipe(ofActionCompleted({ type: '@productStore.addProduct(product, queryParam)' })).subscribe(() => {
       this.pdtTypeState.getShopProductTypes(pdt.shopPdtId).pipe(take(1)).subscribe(()=> {
      this.pdtTypeState.selectProduct({} as ShopProductModel);
       this.pdtAddonState.removeAll()
    })

"dependencies": {
    "@angular/animations": "^9.1.11",
    "@angular/cdk": "^9.2.4",
    "@angular/common": "^9.1.11",
    "@angular/compiler": "^9.1.11",
    "@angular/core": "^9.1.11",
    "@angular/forms": "^9.1.11",
    "@angular/platform-browser": "^9.1.11",
    "@angular/platform-browser-dynamic": "^9.1.11",
    "@angular/router": "^9.1.11",
    "@ngxs-labs/data": "^3.0.5",
    "@ngxs/form-plugin": "^3.6.2",
    "@ngxs/router-plugin": "^3.6.2",
    "@ngxs/storage-plugin": "^3.6.2",
    "@ngxs/store": "^3.6.2",
    "@nrwl/angular": "9.4.3",
    "ng-zorro-antd": "^9.1.2",
    "ngxs-reset-plugin": "^1.3.0",
    "rxjs": "~6.5.4",
    "subsink": "^1.0.1",
    "typeorm": "^0.2.24",
    "zone.js": "^0.10.2"
  },

**Comment by splincode** [comment]
please add repo for reproduce

**Comment by swatiqman** [comment]
> please add repo for reproduce

https://github.com/swatiqman/ngxslab_data_test

please check out the console logs for the error

**Comment by swatiqman** [comment]
it seems you cant call another action in an action handler....is that supposed to be the case?
@splincode  @markwhitfeld @poloagustin

**Comment by splincode** [comment]
Move to https://github.com/Angular-RU/angular-ru-sdk/issues/866
