### ISSUE TITLE
@Computed properties are not updated when using @Debounce

### ISSUE THREAD

**Issue by ionel-fundmore** [ngxs-labs/data#515]
I've been playing locally with the Amount example: `https://github.com/ngxs-labs/data/tree/master/integration/app/src/examples/amount` and noticed that if I use @Debounce:

    @Debounce(3000)
    public setAmount(value: string): void {
        this.setState(parseFloat(value));
    }

in the following file: `https://github.com/ngxs-labs/data/blob/master/integration/app/src/examples/amount/amount.state.ts`
then the UI (Sum) does not get properly updated when changing the second input field (only when doing some clicks in the input fields).

Is this expected?

In my case I'm doing some http calls which take some time and once those are finished then I patch the state. Using @Debounce is just another way to reproduce the issue.

**Comment by splincode** [comment]
try

```
@Debounce(3000)
public setAmount(value: string): void {
    this.setState(parseFloat(value));
    this.cd.detectChanges();
}
```

**Comment by ionel-fundmore** [comment]
I will try this out later today, thank you!

**Comment by ionel-fundmore** [comment]
Small update: I'm still working on adding the `ChangeDetectorRef`, I'm having some issues with it so far:

`[ERROR!]  Error: Uncaught (in promise): NullInjectorError: R3InjectorError(PortalModule)[NgxsFeatureModule -> MortgageApplicationState -> ChangeDetectorRef -> ChangeDetectorRef -> ChangeDetectorRef -> ChangeDetectorRef]: 
  NullInjectorError: No provider for ChangeDetectorRef!
Error: NullInjectorError: No provider for ChangeDetectorRef!
    at NullInjector.get (core.js:914) [angular]
    at R3Injector.get (core.js:11062) [angular]
    at R3Injector.get (core.js:11062) [angular]
    at R3Injector.get (core.js:11062) [angular]
    at NgModuleRef$1.get (core.js:23936) [angular]
    at R3Injector.get (core.js:11062) [angular]
    at injectInjectorOnly (core.js:800) [angular]
    at Module.ɵɵinject (core.js:804) [angular]
    at Object.MortgageApplicationState_Factory [as factory] (mortgage-application.state.ts:24) [angular]
    at R3Injector.hydrate (core.js:11229) [angular]
    at R3Injector.get (core.js:11051) [angular]
    at StateFactory.add (ngxs-store.js:2431) [angular]
    at StateFactory.addAndReturnDefaults (ngxs-store.js:2453) [angular]
    at new NgxsFeatureModule (ngxs-store.js:3385) [angular]
    at resolvePromise (zone-evergreen.js:798) [angular]
    at resolvePromise (zone-evergreen.js:750) [angular]
    at :4201/polyfills.js:873:21 [angular]
    at Object.onInvokeTask (core.js:27137) [angular]
    at drainMicroTaskQueue (zone-evergreen.js:569) [<root>]`

`import { ChangeDetectorRef } from '@angular/core';`

`@Injectable()
export class MortgageApplicationState extends NgxsDataRepository<MortgageApplicationStateModel> {
  constructor(private applicationService: MortgageApplicationService, private cd: ChangeDetectorRef) {
    super();
  }`

**Comment by splincode** [comment]
please create minimal reproduce in stackblitz

**Comment by splincode** [comment]
don't inject `ChangeDetectorRef` in service, because `ChangeDetectorRef` exist only in components.

**Comment by splincode** [comment]
So, I can create new parameter for debounce decorator:
https://github.com/ngxs-labs/data/blob/master/lib/decorators/src/debounce/debounce.ts#L16

For help you

**Comment by ionel-fundmore** [comment]
I've seen that code while reviewing the library. I've also tried `{ insideZone: true }` in that direction:

```
    @DataAction({ insideZone: true })
    public setAmount(value: number) {
        this.setState(value);
    }

    @Debounce(3000)
    public setAmountAsync(value: string): void {
        this.setAmount(parseFloat(value));
    }
```

but I couldn't make it work. I will create something in `stackblitz` in the following days. 

Thank you for your feedback and quick responses!

**Comment by splincode** [comment]
You can create pull request for new feature

```
@Debounce(3000, { insideZone: true })
```

**Comment by splincode** [comment]
Move to https://github.com/Angular-RU/angular-ru-sdk/issues/868
