### ISSUE TITLE
StackBlitz example broken

### ISSUE THREAD

**Issue by ConnerEnders** [ngxs-labs/data#520]
StackBlitz spits out these errors on the page (probably not helpful):

```
Error in integration/app/styles.scss
Error: ENOENT: No such file or directory., '/dev/null'
```

**Comment by splincode** [comment]
Thank you, I will fix it later

**Comment by splincode** [comment]
https://stackblitz.com/edit/ngxs-example-counter-app?file=src/app/count.state.ts
