### ISSUE TITLE
DEPRECATED: DI is instantiating a token "" that inherits its @Injectable decorator but does not provide one itself.     This will become an error in a future version of Angular. Please add @Injectable() to the "" class.

### ISSUE THREAD

**Issue by splincode** [ngxs-labs/data#522]
DEPRECATED: DI is instantiating a token "" that inherits its @Injectable decorator but does not provide one itself.
    This will become an error in a future version of Angular. Please add @Injectable() to the "" class.

**Comment by mflorence99** [comment]
I noticed this error reported in the devtools console, but apparently no ill-effects.

Just a question/data point: could it be related to a bug I'm hitting in my test cases? I'm coding something like this to instantiate a state class for testing:

```ts
const selection = TestBed.inject(SelectionState);
```

This generates: `TypeError: Class constructor SelectionState cannot be invoked without 'new'`

I downgrade to v3 and all works again as normal.

**Comment by splincode** [comment]
No, this is not related to your example. I need to investigate this point, what has changed in the new version of Angular

**Comment by mflorence99** [comment]
Thank you for your reply and sorry to hear about the bug. Would it help if I tried to create a StackBlitz repro case?

**Comment by splincode** [comment]
https://github.com/angular/angular/issues/38966
