### ISSUE TITLE
Setting decode/encode globally does not work

### ISSUE THREAD

**Issue by ishanuda** [ngxs-labs/data#538]
Hi,
Setting the encoding globally does not encode with base64.
However, adding to Persistence locally works fine.

Local Configuration - Successful
```
@Persistence([{
    decode: STORAGE_DECODE_TYPE.BASE64,
}])
```

Global Configuration - Not Successful
```
import {
  NGXS_DATA_STORAGE_PLUGIN,
  NGXS_DATA_STORAGE_DECODE_TYPE,
} from '@ngxs-labs/data/storage';
import { STORAGE_DECODE_TYPE } from '@ngxs-labs/data/typings';
```

```
providers: [
    { provide: NGXS_DATA_STORAGE_DECODE_TYPE, useValue: STORAGE_DECODE_TYPE.BASE64 }
]
```
Also, note that I could only find **NGXS_DATA_STORAGE_DECODE_TYPE** instead of **NGXS_DATA_STORAGE_DECODE_TYPE_TOKEN**

![Typo Error](https://user-images.githubusercontent.com/8893919/93353527-a7d8c300-f859-11ea-8fb0-9f3b2f876276.jpg)

Is this a typo in the documentation?

[MR](https://github.com/ishanuda/ngxs-data-v4.1.1-test-mr-1)

Thank you very much.

**Comment by splincode** [comment]
Maybe this is documentation typo

**Comment by ishanuda** [comment]
Hi,
Have any idea about why the global setting is not working?
Is it a bug in the library?

regards

**Comment by splincode** [comment]
Sorry, I am in vacation. Sorry, I am in vacation

**Comment by splincode** [comment]
Move to https://github.com/Angular-RU/angular-ru-sdk/issues/869
