### ISSUE TITLE
Please Add Autosubscribe for actions like ngxs

### ISSUE THREAD

**Issue by floinay** [ngxs-labs/data#612]
Please add this feature

> You might notice I returned the Observable and just did a tap. If we return the Observable, the framework will automatically subscribe to it for us, so we don't have to deal with that ourselves. Additionally, if we want the stores dispatch function to be able to complete only once the operation is completed, we need to return that so it knows that.

[docs link](https://www.ngxs.io/concepts/state)

**Comment by Beef-Tech** [comment]
+1 please.

**Comment by splincode** [comment]
Move to https://github.com/Angular-RU/angular-ru-sdk/issues/867
