### ISSUE TITLE
Entity array observable

### ISSUE THREAD

**Issue by ada99** [ngxs-labs/data#618]
It would be nice to have something like this:
```javascript 
abstract class AbstractNgxsDataEntityCollectionsRepository ... {
...
    get entitiesArray$(): Observable<V[]> {
        return this.state$.pipe(map(value => value.ids.map(id => value.entities[id])));
    }
}
```

**Comment by splincode** [comment]
@ada99 can you add PR?

Example with

https://github.com/ngxs-labs/data/blob/master/lib/repositories/src/ngxs-data-entity-collections/ngxs-data-entity-collections.repository.ts#L58
