### ISSUE TITLE
@angular-ru as a peer dependency? Why?

### ISSUE THREAD

**Issue by gioele-antoci** [ngxs-labs/data#630]
I am having issues with running the persistance module 
> Error: ./node_modules/@ngxs-labs/data/fesm2015/ngxs-labs-data-repositories.js
Module not found: Error: Can't resolve '@angular-ru/common/utils' in './node_modules/@ngxs-labs/data/fesm2015'

Until I noticed @angular-ru is a peer dependency: https://github.com/ngxs-labs/data/blob/master/lib/package.json#L34

Why would that be the cause? Why not official angular repositories? What am I missing? Do I actually need to install whatever angular-ru is?

**Comment by splincode** [comment]
Because this project will be move to `@angular-ru/ngxs-data` and deprecated `@ngxs-labs/data`

**Comment by gioele-antoci** [comment]
Does this mean that I unless I intend to install @angular-ru I won't be able to use the persistence API? What's the reason to deprecate it from here?

**Comment by splincode** [comment]
because this project is easiest to maintain in another repository where automatic publishing of projects is configured

**Comment by oglezglez** [comment]
You are using this dependency mainly for types definition... as far I see, there is no reason to not use official Angular repositories... and it's not documented... and why?
Do you think it could be fixed?

**Comment by splincode** [comment]
@oglezglez me and my team are working to improve the shared library (`@angular-ru/common`)

in the future this package will be moved and delivered this way

```json
{
  "dependencies": {
    "@angular-ru/common": "....",
    "@angular-ru/ngxs-data-plugin": "....",
  }
}
```

**Comment by ivanblazevic** [comment]
> @oglezglez me and my team are working to improve the shared library (`@angular-ru/common`)
> 
> in the future this package will be moved and delivered this way
> 
> ```json
> {
>   "dependencies": {
>     "@angular-ru/common": "....",
>     "@angular-ru/ngxs-data-plugin": "....",
>   }
> }
> ```

I am not planning to install some strange Russian fork of Angular into my project just for the purpose of having this plugin - after seeing this and the direction where it is going and the though process of its maintainers for me this is clear sign to removing this library from my project and switching back either to ngrx or some alternative.

**Comment by splincode** [comment]
@ivanblazevic up to you))

NGXS Labs is group for experimental projects, but it is my own project)) and `data-plugin` has nothing to do with the NGXS core and is supported by me personally

**Comment by splincode** [comment]
```
{
  "dependencies": {
    "@angular-ru/cdk": "....",
    "@angular-ru/ngxs": "....",
  }
}
```
