### ISSUE TITLE
Angular not supported 

### ISSUE THREAD

**Issue by splincode** [ngxs-labs/data#631]
![image](https://user-images.githubusercontent.com/12021443/112163444-18441080-8bfe-11eb-8b2b-f336fd6554a3.png)

**Comment by marcelpotirnac** [comment]
isn't this resolved by https://github.com/ngxs-labs/data/pull/628 ?

**Comment by splincode** [comment]
@marcelpotirnac yes, but not released yet (((

**Comment by splincode** [comment]
Released 4.2.0
