### ISSUE TITLE
State with @Persistence() decorator initialized with default value.

### ISSUE THREAD

**Issue by floinay** [ngxs-labs/data#632]
Hello, i run console.log(this.snapshot) in my action after app init, but i can see empty object. In the same time in local storage my previously saved object.

**Comment by splincode** [comment]
Hello)) add stackblitz repro please

**Comment by floinay** [comment]
> Hello)) add stackblitz repro please

Sorry, Stackblitz not working with your library( 

I created github repo

https://github.com/floinay/ngxs-labs-data-stackblitz

I created simple state and added simple factory method `fetch`, before setState() i console.log state snapthot.
If APP_INIT provider exists -  first value in state prints empty object every time.

https://github.com/floinay/ngxs-labs-data-stackblitz/blob/main/src/app/app.module.ts
https://github.com/floinay/ngxs-labs-data-stackblitz/blob/main/src/app/tes.state.ts

**Comment by floinay** [comment]
@splincode Hi, can you help me?

**Comment by splincode** [comment]
blocked by https://github.com/ngxs-labs/data/pull/633

**Comment by splincode** [comment]
@floinay hi, could you please upgrade to `@ngxs-labs/data@5.0.0` / `@angular-ru/common@latest` in your demo project?

**Comment by floinay** [comment]
@splincode Hi, works fine, thanks very much)

**Comment by splincode** [comment]
Good news)
