### ISSUE TITLE
@Persistence decorator not working in feature module

### ISSUE THREAD

**Issue by floinay** [ngxs-labs/data#636]
Hi, i try use state with @Persistence in feature module, but in that case storage not working, doesn't even create an entry in localstorage.

https://github.com/floinay/ngxs-labs-data-stackblitz

1. Clone this repo and run project
2. open localhost:4200
3. Open inspect panel and go to the application tab
4. Go to Local Storage page

In this app there is 2 persistence state, "test" in root module and "feature" in feature module, but in local storage exists only "test" data

Thanks 

![image](https://user-images.githubusercontent.com/19957549/113696524-cd84c700-96da-11eb-9fb7-370719358d52.png)

**Comment by splincode** [comment]
@floinay yes, this is regression ((

**Comment by ishanuda** [comment]
@floinay ,
I see few things that should be corrected according to the doc.

1. set state - `this.setState({featureKey1: 'test', key2: 'test1'});` should be `this.ctx.setState({featureKey1: 'test', key2: 'test1'});`
2. `@DataAction()` should be used with the `fetch(): void {}` method

NOTE: `DataAction `can be imported from `'@ngxs-labs/data/decorators';
`
Please try these settings.

regards.

**Comment by floinay** [comment]
> @floinay ,
> I see few things that should be corrected according to the doc in your repo.
> 
> 1. set state - `this.setState({featureKey1: 'test', key2: 'test1'});` should be `this.ctx.setState({featureKey1: 'test', key2: 'test1'});`
> 2. `@DataAction()` should be used with the `fetch(): void {}` method
> 
> NOTE: `DataAction `can be imported from `'@ngxs-labs/data/decorators'; `
> Please try these settings.
> 
> regards.

Hi, i tried, not working

**Comment by splincode** [comment]
@floinay can you help me? create bugfix with PR?

**Comment by strigefleur** [comment]
Any updates? It's kinda problematic to use it without feature modules.

**Comment by splincode** [comment]
Move to https://github.com/Angular-RU/angular-ru-sdk/issues/862

**Comment by splincode** [comment]
Move to https://github.com/Angular-RU/angular-ru-sdk/issues/863
