### ISSUE TITLE
Angular 12 support?

### ISSUE THREAD

**Issue by MohannedElfatih** [ngxs-labs/data#646]
Am getting such errors when using angular 12

> Error: node_modules/@ngxs-labs/data/internals/services/ngxs-data-computed-stream.service.d.ts:12:21 - error TS2694: Namespace '"C:/Users/Mohanned/Documents/GitHub/pass-management/node_modules/@angular/core/core"' has no exported member 'ɵɵFactoryDef'.

**Comment by splincode** [comment]
In next week I will update this package for Angular 12

**Comment by vutukuriajay2241** [comment]
I am also facing this error. When this will be resolved?


Error: node_modules/@ngxs-labs/data/internals/services/ngxs-data-computed-stream.service.d.ts:13:22 - error TS2724:  has no exported member named 'ɵɵInjectableDef'. Did you mean 'ɵgetInjectableDef'?
static ɵprov: i0.ɵɵInjectableDef<NgxsDataSequence>;


Error: node_modules/@ngxs-labs/data/internals/services/ngxs-data-factory.service.d.ts:18:21 - error TS2694: Namespace has no exported member 'ɵɵFactoryDef'.
static ɵfac: i0.ɵɵFactoryDef<NgxsDataFactory, never>;
 
Error: node_modules/@ngxs-labs/data/internals/services/ngxs-data-factory.service.d.ts:19:22 - error TS2724: has no exported member named 'ɵɵInjectableDef'. Did you mean 'ɵgetInjectableDef'?

 static ɵprov: i0.ɵɵInjectableDef<NgxsDataFactory>;
                        ~~~~~~~~~~~~~~~


Error: node_modules/@ngxs-labs/data/internals/services/ngxs-data-injector.service.d.ts:13:21 - error TS2694: Namespace ' has no exported member 'ɵɵFactoryDef'.

 static ɵfac: i0.ɵɵFactoryDef<NgxsDataInjector, never>;
                       ~~~~~~~~~~~~


Error: node_modules/@ngxs-labs/data/internals/services/ngxs-data-injector.service.d.ts:14:22 - error TS2724:  has no exported member named 'ɵɵInjectableDef'. Did you mean 'ɵgetInjectableDef'?

 static ɵprov: i0.ɵɵInjectableDef<NgxsDataInjector>;
                        ~~~~~~~~~~~~~~~


Error: node_modules/@ngxs-labs/data/src/ngxs-data.module.d.ts:10:21 - error TS2694: Namespace  has no exported member 'ɵɵFactoryDef'.

static ɵfac: i0.ɵɵFactoryDef<NgxsDataPluginModule, [{ self: true; }, { self: true; }]>;
                       ~~~~~~~~~~~~


Error: node_modules/@ngxs-labs/data/src/ngxs-data.module.d.ts:11:21 - error TS2694: Namespace has no exported member 'ɵɵNgModuleDefWithMeta'.

 static ɵmod: i0.ɵɵNgModuleDefWithMeta<NgxsDataPluginModule, never, never, never>;

**Comment by splincode** [comment]
@vutukuriajay2241 please create minimal github repository for reproduce

**Comment by vutukuriajay2241** [comment]
Didn’t get you

**Comment by splincode** [comment]
I don't have problem with install last package version, if you have a problem with your project, should be get simple example for reproduce

**Comment by vutukuriajay2241** [comment]
Thanks working well
