### ISSUE TITLE
removeAll resets the state to its initial value instead of removing all entities

### ISSUE THREAD

**Issue by krtek4** [ngxs-labs/data#647]
From the documentation :

>  state.removeAll() | void | Remove all entities from the collection

But if we look at the code :

```
    @DataAction()
    public removeAll(): void {
        this.setEntitiesState(this.initialState);
    }
```

My understanding is that "Remove all entities from the state" will only clear the `entities` attribute of the state and not reset the state to its initial value.

Also, this is misleading if the initialState contains entities, `removeAll` would then "leave" entities in the state.

**Comment by splincode** [comment]
we can add breaking changes

**Comment by krtek4** [comment]
you probably mean "can't add" ;)

But you can update the documentation to explain the the real behaviour.

**Comment by splincode** [comment]
Move to
https://github.com/Angular-RU/angular-ru-sdk/issues/861
