### ISSUE TITLE
pushStateToStorage errors

### ISSUE THREAD

**Issue by strigefleur** [ngxs-labs/data#663]
Having
```
NgxsModule.forRoot(InitStates),
NgxsDataPluginModule.forRoot([NGXS_DATA_STORAGE_EXTENSION, NGXS_DATA_STORAGE_CONTAINER]),
// ...
{ provide: NGXS_DATA_STORAGE_PREFIX_TOKEN, useValue: '@some.store.' },
```
where `InitStates` is array containing some states.

Gives me multiple `prop is null` errors on `pushStateToStorage` function line
`const prevData = getValue(states, ensurePath(provider));`
on page load/refresh.

![изображение](https://user-images.githubusercontent.com/20131398/123797461-ddcdcc00-d8ee-11eb-9c17-c1707222d9fd.png)

**Comment by splincode** [comment]
please provide github repo for reproduce

**Comment by strigefleur** [comment]
It appears that
```
export const InitStates = [
    AlphaState,
    BetaState,
]
// ... 
NgxsModule.forRoot(InitStates),
```
is not the same as
```
NgxsModule.forRoot([AlphaState, BetaState]),
```

Using case 1 I got the errors mentioned, case 2 gives no errors.
I'm still confused since I can't reproduce it on a clean project.
