### ISSUE TITLE
Add NgxsEntityRepository

### ISSUE THREAD

**Issue by splincode** [ngxs-labs/data#86]

**Comment by splincode** [comment]
Adapter Collection Methods
The entity adapter also provides methods for operations against an entity. These methods can change one to many records at a time. Each method returns the newly modified state if changes were made and the same state if no changes were made.

addOne: Add one entity to the collection
addMany: Add multiple entities to the collection
addAll: Replace current collection with provided collection
setOne: Add or Replace one entity in the collection
removeOne: Remove one entity from the collection
removeMany: Remove multiple entities from the collection, by id or by predicate
removeAll: Clear entity collection
updateOne: Update one entity in the collection. Supports partial updates.
updateMany: Update multiple entities in the collection. Supports partial updates.
upsertOne: Add or Update one entity in the collection. Supports partial updates.
upsertMany: Add or Update multiple entities in the collection. Supports partial updates.
map: Update multiple entities in the collection by defining a map function, similar to Array.map


```ts
type EntityIdType = string | number;

export interface EntityCollections<V, K= EntityIdType> {
  ids: K[];
  entities: V[];
}

class NgxsDataEntityCollectionsRepository<V, K = EntityIdType> {

}


```

**Comment by ceyhunn** [comment]
Hi @splincode , if you add this one, I will really get pleasant, because I am backend developer. I use repository classes in Java. When will this feature be ready approximately?

**Comment by ceyhunn** [comment]
I like entity data plugin, but it isn't production ready yet, is it?

**Comment by splincode** [comment]
I'm Java/Kotlin developer too

@ceyhunn If you have ideas on the entity adapter, then I am ready to hear your ideas

**Comment by splincode** [comment]
@ceyhunn Hi, I released `@ngxs-labs/data@3.0.0-rc.10`

You can try new API for manipulation entities

![image](https://user-images.githubusercontent.com/12021443/79374225-dcb9b480-7f5f-11ea-9290-d668e23480d0.png)

PS: I would be glad if you tested the new API and helped find any bugs or suggest improvements on entity manipulation

**Comment by ceyhunn** [comment]
Hi @splincode , Thank you so much. Why you don't add selectById, selectAll...? I mean selectors. Is it not possible?

**Comment by splincode** [comment]
show me example

**Comment by xban1x** [comment]
> show me example

I think he is talking basically about common read Actions like you have in TypeORM where you can use `find` and `findOne`

**Comment by ceyhunn** [comment]
> show me example

You know jpa repositories in Java web. Similar to this.

**Comment by splincode** [comment]
I don't love JPA, I use JDBC every where, because JPA is bad wat

**Comment by splincode** [comment]
So, I understand you `selectOne, selectAll`. I will add later

**Comment by ceyhunn** [comment]
@splincode , how do I add custom properties to EntityCollection?
for example:
{
     ids: K[],
     entities: T[],
     filter: any,
     count: number,
     pageIndex: number,
     pageSize: number
}
Using another state?

**Comment by splincode** [comment]
I would not really like it to be added like this

what is it for? this will complicate the interaction with the state

```ts
     filter: any,
     count: number,
     pageIndex: number,
     pageSize: number
```

You can try

```ts
@Injectable()
export abstract class MyEntitiesRepository<T> extends NgxsDataEntityCollectionsRepository<T> implements NgxsDataDoCheck, NgxsDataAfterReset {
   public innerState = {
      filter: any,
      count: number,
      pageIndex: number,
      pageSize: number
   };

   private subscription: Subscribption;

   public ngxsDataDoCheck() {
      this.subscription = this.state$.subscribe((state) => {
          // manipulte with this.innerState
      });
   }

   public ngxsDataAfterReset(): void {
     this.subscription.unsubscribe();
   }

}
```

```ts
@@StateRepository()
@State({
    name: 'lessons',
    defaults: createEntityCollections()
})
@Injectable()
export class LessonEntitiesState extends MyEntitiesRepository<Model> {}
```

**Comment by ceyhunn** [comment]
> what is it for? this will complicate the interaction with the state

I used another state for filter, sort and page parameters. Purpose is that for this parameters to get data from api service, then set response data in entity collection state.

**Comment by xban1x** [comment]
You should create separate state for pagination, sort, filters and have them communicate with the repository part which executes requests to server

**Comment by ceyhunn** [comment]
Yes, I have already done it, thank you for all suggestions.

**Comment by splincode** [comment]
@ceyhunn Please can you give an example of how you use these fields with entities

```ts
  filter: any,
     count: number,
     pageIndex: number,
     pageSize: number
```

```ts

interface EntityOptions {
    filter: any,
     count: number,
     pageIndex: number,
     pageSize: number
}

@StateRepository()
@State({
    name: 'lessonOptions',
    defaults: {
        filter: null,
        count: 0,
        pageIndex: 0,
        pageSize: 0
    }
})
@Injectable()
export class LessonEntitiesState extends DataRepository<EntityOptions> {}

interface Options {
  lessonOptions: EntityOptions;
}

@StateRepository()
@State({
    name: 'lessons',
    defaults: createEntityCollections()
    children: [LessonEntityOptions]
})
@Injectable()
export class LessonEntitiesState extends MyEntitiesRepository<Model, number, Options> {}
```

**Comment by ceyhunn** [comment]
@splincode , I don't understand your code. I did like this:
1. I have two states:
```
interface LessonsStateModel {
     filter: any,
     count: number,
     pageIndex: number,
     pageSize: number
}
LessonsState extends  NgxsDataRepository<LessonsStateModel>
LessonEntitiesState extends NgxsDataEntityCollectionsRepository<LessonModel>
```

**Comment by splincode** [comment]
how do you synchronizing LessonState and LessonEntitiesState?
