### ISSUE TITLE
Error with typescript v3.5.3 when compiling ngxs-labs/data v2.1.3

### ISSUE THREAD

**Issue by ishanuda** [ngxs-labs/data#95]
Error with typescript v3.5.3 when compiling

![error](https://user-images.githubusercontent.com/8893919/71305801-dcb90600-23fe-11ea-99b5-2a616674810d.jpg)

Dependencies in the project
![ng-error](https://user-images.githubusercontent.com/8893919/71305847-594be480-23ff-11ea-9094-e9a027d61316.jpg)

NOTE: I tried to update the typescript to v3.7.4 but after that, I get the angular compiler error as above in the image so I rollbacked to v3.5.3
NodeJS version is 10.16.3

regards.
Shan

**Comment by splincode** [comment]
@ishanuda please create minimal repo for reproduce

**Comment by splincode** [comment]
@ishanuda try version `2.1.4`
